language: go

before_install:
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  # Test deps
  - go get github.com/stretchr/testify
  # Linting deps
  - go get github.com/alecthomas/gometalinter
  - gometalinter --install

script:
  - gometalinter --fast ./...
  - go test -v ./...
  - go test -covermode=count -coverprofile=profile.cov

after_script:
  - $HOME/gopath/bin/goveralls -coverprofile=profile.cov -service=travis-ci
